# Generated by Django 5.0.2 on 2025-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Referee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="referees/photos/",
                        verbose_name="Фото",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="Национальность"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("international", "Международный"),
                            ("national", "Национальный"),
                            ("regional", "Региональный"),
                        ],
                        default="national",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Опыт работы (лет)"
                    ),
                ),
                (
                    "matches_officiated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Отсужденные матчи"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Судья",
                "verbose_name_plural": "Судьи",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
