# Generated by Django 5.0.2 on 2025-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Национальность"
            ),
        ),
    ]
