# Generated by Django 5.0.2 on 2025-09-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0002_alter_referee_date_of_birth_alter_referee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='experience_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт (в месяцах)'),
        ),
        migrations.AddField(
            model_name='referee',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='referee',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регион / город'),
        ),
    ]
