# Generated by Django 5.0.2 on 2025-09-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referees", "0003_referee_experience_months_referee_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referee",
            name="category",
            field=models.CharField(
                choices=[
                    ("international", "Международный"),
                    ("national", "Национальный"),
                    ("regional", "Региональный"),
                ],
                default="national",
                help_text="Категория судьи (международный, национальный, региональный)",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="experience_months",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Опыт работы судьей в месяцах",
                verbose_name="Опыт (месяцы)",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="first_name",
            field=models.CharField(
                help_text="Имя судьи", max_length=100, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="last_name",
            field=models.CharField(
                help_text="Фамилия судьи", max_length=100, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Контактный телефон",
                max_length=32,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Фотография судьи",
                null=True,
                upload_to="referees/photos/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Место проживания или работы судьи",
                max_length=100,
                verbose_name="Регион / город",
            ),
        ),
    ]
