# Generated by Django 5.0.2 on 2025-09-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referees", "0004_alter_referee_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referee",
            name="category",
            field=models.CharField(
                choices=[
                    ("chief", "Главный судья"),
                    ("assistant", "Помощник"),
                    ("var", "VAR"),
                    ("inspector", "Инспектор"),
                ],
                default="chief",
                help_text="Главный судья / Помощник / VAR / Инспектор",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="photo",
            field=models.ImageField(
                help_text="Фотография судьи",
                upload_to="referees/photos/",
                verbose_name="Фото",
            ),
        ),
    ]
