# Generated by Django 5.1.4 on 2025-09-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referees", "0005_alter_referee_category_alter_referee_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referee",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Фотография судьи (необязательно)",
                null=True,
                upload_to="referees/photos/",
                verbose_name="Фото",
            ),
        ),
    ]
