# Generated by Django 5.0.2 on 2025-08-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_matches",
                    models.PositiveIntegerField(default=0, verbose_name="Всего матчей"),
                ),
                (
                    "total_goals",
                    models.PositiveIntegerField(default=0, verbose_name="Всего голов"),
                ),
                (
                    "total_attendance",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Общая посещаемость"
                    ),
                ),
                (
                    "average_goals_per_match",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        verbose_name="Среднее количество голов за матч",
                    ),
                ),
                (
                    "average_attendance_per_match",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Средняя посещаемость за матч"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "season",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика сезона",
                "verbose_name_plural": "Статистика сезонов",
            },
        ),
        migrations.CreateModel(
            name="ClubStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matches_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Сыгранные матчи"
                    ),
                ),
                ("wins", models.PositiveIntegerField(default=0, verbose_name="Победы")),
                ("draws", models.PositiveIntegerField(default=0, verbose_name="Ничьи")),
                (
                    "losses",
                    models.PositiveIntegerField(default=0, verbose_name="Поражения"),
                ),
                (
                    "goals_for",
                    models.PositiveIntegerField(default=0, verbose_name="Забитые голы"),
                ),
                (
                    "goals_against",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Пропущенные голы"
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0, verbose_name="Очки")),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Позиция"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_statistics",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика клуба",
                "verbose_name_plural": "Статистика клубов",
                "ordering": ["season", "position", "-points"],
                "unique_together": {("club", "season")},
            },
        ),
    ]
