# Generated by Django 5.0.2 on 2025-08-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="players/photos/",
                        verbose_name="Фото",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="Национальность"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "Вратарь"),
                            ("DF", "Защитник"),
                            ("MF", "Полузащитник"),
                            ("FW", "Нападающий"),
                        ],
                        max_length=2,
                        verbose_name="Позиция",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Рост (см)"
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Вес (кг)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
                "ordering": ["last_name", "first_name"],
                "unique_together": {("club", "season", "number")},
            },
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matches_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Сыгранные матчи"
                    ),
                ),
                (
                    "matches_started",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Матчи в старте"
                    ),
                ),
                (
                    "minutes_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Минуты на поле"
                    ),
                ),
                ("goals", models.PositiveIntegerField(default=0, verbose_name="Голы")),
                (
                    "assists",
                    models.PositiveIntegerField(default=0, verbose_name="Передачи"),
                ),
                (
                    "yellow_cards",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Желтые карточки"
                    ),
                ),
                (
                    "red_cards",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Красные карточки"
                    ),
                ),
                (
                    "clean_sheets",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Сухие матчи (для вратарей)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="players.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика игрока",
                "verbose_name_plural": "Статистика игроков",
                "ordering": ["season", "player"],
                "unique_together": {("player", "season")},
            },
        ),
    ]
