# Generated by Django 5.0.2 on 2025-09-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_alter_club_city_alter_coach_first_name_and_more"),
        ("core", "0003_remove_media_description_alter_management_name_and_more"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="clubs.club",
                verbose_name="Клуб",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="player",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Национальность"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GK", "Вратарь"),
                    ("DF", "Защитник"),
                    ("MF", "Полузащитник"),
                    ("FW", "Нападающий"),
                ],
                max_length=2,
                verbose_name="Позиция",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="core.season",
                verbose_name="Сезон",
            ),
        ),
    ]
