# Generated by Django 5.0.2 on 2025-09-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_club_alter_player_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="player",
            unique_together=set(),
        ),
    ]
