# Generated by Django 5.0.2 on 2025-09-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_assistant_full_name_club_captain_full_name_and_more'),
        ('players', '0003_alter_player_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(blank=True, choices=[('applied', 'Заявлен'), ('active', 'Активен'), ('injured', 'Травма'), ('disqualified', 'Дисквалифицирован'), ('loan', 'Аренда'), ('withdrawn', 'Выбыл')], default='active', max_length=32, verbose_name='Статус игрока'),
        ),
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(verbose_name='Дата перехода')),
                ('status', models.CharField(choices=[('confirmed', 'Подтвержден'), ('pending', 'Ожидание'), ('cancelled', 'Отменен')], default='pending', max_length=16, verbose_name='Статус трансфера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('from_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='clubs.club', verbose_name='Из команды')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='players.player', verbose_name='Игрок')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='clubs.club', verbose_name='В команду')),
            ],
            options={
                'verbose_name': 'Трансфер игрока',
                'verbose_name_plural': 'Трансферы игроков',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
    ]
