# Generated by Django 5.0.2 on 2025-09-03 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_remove_club_colors_remove_club_kit_color_away_and_more"),
        ("core", "0006_management_notes_alter_management_name_and_more"),
        ("players", "0004_player_phone_player_status_playertransfer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playertransfer",
            options={
                "ordering": ["-transfer_date"],
                "verbose_name": "Трансфер игрока",
                "verbose_name_plural": "Трансферы игроков",
            },
        ),
        migrations.AddField(
            model_name="player",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Особые условия, травмы, аренда",
                verbose_name="Примечание",
            ),
        ),
        migrations.AddField(
            model_name="playertransfer",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Дополнительная информация о трансфере",
                verbose_name="Примечания",
            ),
        ),
        migrations.AddField(
            model_name="playertransfer",
            name="transfer_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="В долларах США",
                max_digits=10,
                null=True,
                verbose_name="Сумма трансфера",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="Привязка к команде",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="clubs.club",
                verbose_name="Команда",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="date_of_birth",
            field=models.DateField(
                help_text="ДД-ММ-ГГГГ", verbose_name="Дата рождения"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="player",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, help_text="Опционально", null=True, verbose_name="Рост (см)"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="player",
            name="nationality",
            field=models.CharField(
                blank=True,
                help_text="Опционально",
                max_length=100,
                verbose_name="Гражданство",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="number",
            field=models.PositiveIntegerField(
                help_text="От 1 до 99", verbose_name="Игровой номер"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Для связи при необходимости",
                max_length=32,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                default="default-player-photo.png",
                help_text="Обязательно",
                upload_to="players/photos/",
                verbose_name="Фото игрока",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("GK", "Вратарь"),
                    ("DF", "Защитник"),
                    ("MF", "Полузащитник"),
                    ("FW", "Нападающий"),
                ],
                help_text="Вратарь / Защитник / Полузащитник / Нападающий",
                max_length=2,
                verbose_name="Амплуа (позиция)",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Заявлен"),
                    ("active", "Активен"),
                    ("injured", "Травма"),
                    ("disqualified", "Дисквалификация"),
                    ("loan", "Аренда"),
                    ("withdrawn", "Выбыл"),
                ],
                default="applied",
                max_length=32,
                verbose_name="Статус игрока",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="weight",
            field=models.PositiveIntegerField(
                blank=True, help_text="Опционально", null=True, verbose_name="Вес (кг)"
            ),
        ),
        migrations.AlterField(
            model_name="playertransfer",
            name="from_club",
            field=models.ForeignKey(
                blank=True,
                help_text="Если игрок свободный агент, поле может быть пустым",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_transfers",
                to="clubs.club",
                verbose_name="Из команды",
            ),
        ),
        migrations.AlterField(
            model_name="playertransfer",
            name="player",
            field=models.ForeignKey(
                help_text="К какому игроку относится трансфер",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="players.player",
                verbose_name="Игрок",
            ),
        ),
        migrations.AlterField(
            model_name="playertransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Подтвержден"),
                    ("pending", "Ожидание"),
                    ("cancelled", "Отменен"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус трансфера",
            ),
        ),
        migrations.AlterField(
            model_name="playertransfer",
            name="to_club",
            field=models.ForeignKey(
                help_text="Куда перешёл игрок",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transfers",
                to="clubs.club",
                verbose_name="В команду",
            ),
        ),
        migrations.AlterField(
            model_name="playertransfer",
            name="transfer_date",
            field=models.DateField(
                help_text="ДД-ММ-ГГГГ Когда состоялся переход",
                verbose_name="Дата перехода",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("club", "season", "number"),
                name="unique_club_season_number",
                violation_error_message="Игровой номер должен быть уникален в рамках клуба и сезона.",
            ),
        ),
    ]
