# Generated by Django 5.0.2 on 2025-09-05 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_alter_playertransfer_options_player_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="number",
            field=models.PositiveIntegerField(
                help_text="От 1 до 99",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Игровой номер",
            ),
        ),
    ]
