# Generated by Django 5.1.4 on 2025-09-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_alter_player_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Для связи при необходимости",
                max_length=32,
                null=True,
                verbose_name="Телефон",
            ),
        ),
    ]
