# Generated by Django 5.1.4 on 2025-09-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_media_image_media_description_media_file_and_more"),
        ("players", "0007_alter_player_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertransfer",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="Сезон, в котором произошел трансфер",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="core.season",
                verbose_name="Сезон",
            ),
        ),
    ]
