# Generated by Django 5.1.4 on 2025-09-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0008_playertransfer_season"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playertransfer",
            name="season",
        ),
        migrations.AlterField(
            model_name="player",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Особые условия, травмы, аренда",
                null=True,
                verbose_name="Примечание",
            ),
        ),
    ]
