# Generated by Django 5.1.4 on 2025-09-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_media_options_remove_media_order_and_more"),
        ("players", "0010_playertransfer_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playertransfer",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="В каком сезоне произошел трансфер",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="core.season",
                verbose_name="Сезон",
            ),
        ),
    ]
