# Generated by Django 5.1.4 on 2025-09-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0011_alter_playertransfer_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Необязательно",
                null=True,
                upload_to="players/photos/",
                verbose_name="Фото игрока",
            ),
        ),
    ]
