# Generated by Django 5.0.2 on 2025-08-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Краткое название"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(upload_to="clubs/logos/", verbose_name="Логотип"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "founded",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год основания"
                    ),
                ),
                (
                    "stadium",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Стадион"
                    ),
                ),
                (
                    "stadium_capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Вместимость стадиона"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "colors",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Цвета клуба"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Клуб",
                "verbose_name_plural": "Клубы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="coaches/photos/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Национальность"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Тренер",
                "verbose_name_plural": "Тренеры",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ClubSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0, verbose_name="Очки")),
                (
                    "matches_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Сыгранные матчи"
                    ),
                ),
                ("wins", models.PositiveIntegerField(default=0, verbose_name="Победы")),
                ("draws", models.PositiveIntegerField(default=0, verbose_name="Ничьи")),
                (
                    "losses",
                    models.PositiveIntegerField(default=0, verbose_name="Поражения"),
                ),
                (
                    "goals_for",
                    models.PositiveIntegerField(default=0, verbose_name="Забитые голы"),
                ),
                (
                    "goals_against",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Пропущенные голы"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Позиция в таблице"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клуб в сезоне",
                "verbose_name_plural": "Клубы в сезонах",
                "ordering": ["season", "position", "points"],
            },
        ),
    ]
