# Generated by Django 5.0.2 on 2025-08-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubseason",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clubs",
                to="core.season",
                verbose_name="Сезон",
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coaches",
                to="clubs.club",
                verbose_name="Клуб",
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coaches",
                to="core.season",
                verbose_name="Сезон",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clubseason",
            unique_together={("club", "season")},
        ),
        migrations.AlterUniqueTogether(
            name="coach",
            unique_together={("club", "season")},
        ),
    ]
