# Generated by Django 5.0.2 on 2025-08-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="clubs/logos/", verbose_name="Логотип"
            ),
        ),
    ]
