# Generated by Django 5.0.2 on 2025-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_alter_club_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="coach",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="coach",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Фамилия"),
        ),
    ]
