# Generated by Django 5.0.2 on 2025-09-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_alter_club_city_alter_coach_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="assistant_full_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="Ассистент тренера / менеджер (ФИО)",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="captain_full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Капитан команды (ФИО)"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="coach_full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Тренер (ФИО)"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email контактного лица"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Телефон контактного лица"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="kit_color_away",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Цвета формы (запасная)"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="kit_color_home",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Цвета формы (основная)"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="participation_fee",
            field=models.BooleanField(default=False, verbose_name="Взнос на участие"),
        ),
        migrations.AddField(
            model_name="club",
            name="short_description",
            field=models.TextField(
                blank=True, verbose_name="Описание / краткая информация"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="socials",
            field=models.URLField(blank=True, verbose_name="Соцсети / сайт"),
        ),
        migrations.AddField(
            model_name="club",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("applied", "Подана заявка"),
                    ("active", "Активна"),
                    ("disqualified", "Дисквалифицирована"),
                    ("withdrawn", "Выбыла"),
                ],
                default="active",
                max_length=32,
                verbose_name="Статус команды",
            ),
        ),
    ]
