# Generated by Django 5.0.2 on 2025-09-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_club_assistant_full_name_club_captain_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="club",
            name="kit_color_away",
        ),
        migrations.RemoveField(
            model_name="club",
            name="kit_color_home",
        ),
        migrations.RemoveField(
            model_name="club",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="club",
            name="socials",
        ),
        migrations.RemoveField(
            model_name="club",
            name="stadium",
        ),
        migrations.RemoveField(
            model_name="club",
            name="stadium_capacity",
        ),
        migrations.AddField(
            model_name="club",
            name="primary_kit_color",
            field=models.CharField(
                blank=True,
                help_text="Можно указать HEX или словом",
                max_length=50,
                verbose_name="Цвета формы (основная)",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="secondary_kit_color",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Цвета формы (запасная)"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="social_media",
            field=models.URLField(
                blank=True,
                help_text="Instagram, Facebook и т.д.",
                verbose_name="Соцсети",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="assistant_full_name",
            field=models.CharField(
                max_length=150, verbose_name="Ассистент тренера / менеджер"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="captain_full_name",
            field=models.CharField(
                blank=True,
                help_text="Опционально",
                max_length=150,
                verbose_name="Капитан команды (ФИО)",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Например: Бишкек",
                max_length=100,
                verbose_name="Город / регион",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="coach_full_name",
            field=models.CharField(
                help_text="Главный тренер", max_length=150, verbose_name="Тренер (ФИО)"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Опционально",
                max_length=254,
                verbose_name="Email контактного лица",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="contact_phone",
            field=models.CharField(
                help_text="Для связи с организаторами",
                max_length=32,
                verbose_name="Телефон контактного лица",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Опционально",
                verbose_name="Описание / краткая информация",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="founded",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Опционально",
                null=True,
                verbose_name="Год основания",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="default-club-logo.png",
                help_text="PNG/JPG, ограничение по размеру",
                null=True,
                upload_to="clubs/logos/",
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(
                help_text="Отображается в списках и на сайте",
                max_length=200,
                verbose_name="Название команды",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="participation_fee",
            field=models.CharField(
                choices=[("yes", "Есть"), ("no", "Нет"), ("partial", "Частично")],
                default="no",
                max_length=20,
                verbose_name="Взнос на участие",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Подана заявка"),
                    ("active", "Активна"),
                    ("disqualified", "Дисквалифицирована"),
                    ("withdrawn", "Выбыла"),
                ],
                default="applied",
                max_length=32,
                verbose_name="Статус команды",
            ),
        ),
    ]
