# Generated by Django 5.0.2 on 2025-09-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_remove_club_colors_remove_club_kit_color_away_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubseason",
            name="games",
            field=models.PositiveIntegerField(default=0, verbose_name="Игры"),
        ),
    ]
