# Generated by Django 5.0.2 on 2025-09-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_clubseason_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubseason",
            name="goal_difference",
            field=models.IntegerField(default=0, verbose_name="Разница мячей"),
        ),
    ]
