# Generated by Django 5.0.2 on 2025-09-03 14:25

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_clubseason_goal_difference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=models.FileField(
                blank=True,
                default="default-club-logo.png",
                help_text="SVG/PNG/WEBP/JPEG",
                null=True,
                upload_to="clubs/logos/",
                validators=[clubs.models.validate_logo_content_type],
                verbose_name="Логотип",
            ),
        ),
    ]
