# Generated by Django 5.0.2 on 2025-09-05 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0009_alter_club_logo"),
        ("core", "0007_delete_management_delete_referee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club_name",
                    models.CharField(
                        help_text="Официальное название клуба",
                        max_length=200,
                        verbose_name="Название клуба",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Краткое название"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город/регион")),
                (
                    "founded",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год основания"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=200, verbose_name="Контактное лицо"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=32, verbose_name="Контактный телефон"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Контактный email"
                    ),
                ),
                (
                    "coach_name",
                    models.CharField(max_length=200, verbose_name="Главный тренер"),
                ),
                (
                    "assistant_coach",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ассистент тренера"
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/logos/",
                        verbose_name="Логотип клуба",
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/documents/",
                        verbose_name="Документы клуба",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает рассмотрения"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                            ("withdrawn", "Отозвана"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание клуба"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Примечания администратора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата подачи заявки"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата рассмотрения"
                    ),
                ),
                (
                    "club",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="clubs.club",
                        verbose_name="Созданный клуб",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Рассмотрел",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка клуба",
                "verbose_name_plural": "Заявки клубов",
                "ordering": ["-created_at"],
            },
        ),
    ]
