# Generated by Django 5.0.2 on 2025-09-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0010_clubapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Автоматически генерируется из названия",
                max_length=200,
                unique=True,
                verbose_name="Slug для URL",
            ),
        ),
    ]
