# Generated by Django 5.0.2 on 2025-09-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0011_club_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="slug",
        ),
    ]
