# Generated by Django 5.1.4 on 2025-09-15 23:37

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0012_remove_club_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="SVG/PNG/WEBP/JPEG (необязательно)",
                null=True,
                upload_to="clubs/logos/",
                validators=[clubs.models.validate_logo_content_type],
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="clubapplication",
            name="documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applications/documents/",
                verbose_name="Документы клуба (необязательно)",
            ),
        ),
    ]
