# Generated by Django 5.1.4 on 2025-09-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0013_alter_club_logo_alter_clubapplication_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Для связи с организаторами",
                max_length=32,
                verbose_name="Телефон контактного лица",
            ),
        ),
        migrations.AlterField(
            model_name="clubapplication",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Контактный телефон"
            ),
        ),
    ]
