# Generated by Django 5.0.7 on 2025-11-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0014_alter_club_contact_phone_and_more"),
        ("core", "0014_season_format_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubseason",
            options={
                "ordering": ["season", "group", "position", "points"],
                "verbose_name": "Клуб в сезоне",
                "verbose_name_plural": "Клубы в сезонах",
            },
        ),
        migrations.AddField(
            model_name="clubseason",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Группа для групповых этапов. Если не указана - обычная таблица.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_seasons",
                to="core.group",
                verbose_name="Группа",
            ),
        ),
    ]
