# Generated by Django 5.0.7 on 2025-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0015_alter_clubseason_options_clubseason_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="assistant_full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Ассистент тренера / менеджер"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="coach_full_name",
            field=models.CharField(
                blank=True,
                help_text="Главный тренер",
                max_length=150,
                verbose_name="Тренер (ФИО)",
            ),
        ),
    ]
