# Generated by Django 5.0.2 on 2025-08-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="management/", verbose_name="Фото"
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Руководство",
                "verbose_name_plural": "Руководство",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(upload_to="media/", verbose_name="Изображение"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gallery", "Галерея"),
                            ("news", "Новости"),
                            ("events", "События"),
                            ("other", "Другое"),
                        ],
                        default="gallery",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Медиа файл",
                "verbose_name_plural": "Медиа файлы",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="referees/", verbose_name="Фото"
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Опыт работы (лет)"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Судья",
                "verbose_name_plural": "Судьи",
                "ordering": ["order", "name"],
            },
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
