# Generated by Django 5.0.2 on 2025-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_management_media_referee_delete_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="description",
        ),
        migrations.AlterField(
            model_name="management",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="management",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gallery", "Галерея"),
                    ("news", "Новости"),
                    ("events", "События"),
                    ("other", "Другое"),
                ],
                default="gallery",
                max_length=50,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("main", "Главный партнер"),
                    ("official", "Официальный партнер"),
                    ("technical", "Технический партнер"),
                ],
                default="official",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="partners/", verbose_name="Логотип"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
    ]
