# Generated by Django 5.0.2 on 2025-09-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_media_description_alter_management_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="management",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="management/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="referees/", verbose_name="Фото"
            ),
        ),
    ]
