# Generated by Django 5.0.2 on 2025-09-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_management_photo_alter_media_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
