# Generated by Django 5.0.2 on 2025-09-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="management",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Дополнительная информация",
                verbose_name="Примечания",
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="name",
            field=models.CharField(
                help_text="Полное имя представителя руководства",
                max_length=200,
                verbose_name="ФИО",
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Контактный телефон",
                max_length=20,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Фотография представителя руководства",
                null=True,
                upload_to="management/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="position",
            field=models.CharField(
                help_text="Должность в руководстве лиги",
                max_length=100,
                verbose_name="Должность",
            ),
        ),
    ]
