# Generated by Django 5.0.2 on 2025-09-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_management_notes_alter_management_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Management",
        ),
        migrations.DeleteModel(
            name="Referee",
        ),
    ]
