# Generated by Django 5.1.4 on 2025-09-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_delete_management_delete_referee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="image",
        ),
        migrations.AddField(
            model_name="media",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="media",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/",
                verbose_name="Файл (для изображений)",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "Изображение"),
                    ("video", "Видео (ссылка)"),
                    ("document", "Документ (ссылка)"),
                ],
                default="image",
                max_length=10,
                verbose_name="Тип медиа",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Например, ссылка на YouTube видео или Google Docs документ",
                verbose_name="URL (для видео/документов)",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="contact_info",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Контактная информация (телефон, email)",
            ),
        ),
    ]
