# Generated by Django 5.1.4 on 2025-09-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_media_image_media_description_media_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Медиа",
                "verbose_name_plural": "Медиа",
            },
        ),
    ]
