# Generated by Django 5.1.4 on 2025-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_media_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="category",
        ),
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="media/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="media",
            name="url",
            field=models.URLField(
                blank=True, verbose_name="Внешняя ссылка (для видео)"
            ),
        ),
    ]
