# Generated by Django 5.1.4 on 2025-09-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_media_category_alter_media_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Медиа файл",
                "verbose_name_plural": "Медиа файлы",
            },
        ),
        migrations.RemoveField(
            model_name="media",
            name="order",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="contact_info",
        ),
        migrations.AlterField(
            model_name="media",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "Изображение"),
                    ("video", "Видео"),
                    ("document", "Документ"),
                ],
                default="image",
                max_length=20,
                verbose_name="Тип медиа",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
    ]
