# Generated by Django 5.1.4 on 2025-09-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_media_options_remove_media_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/",
                verbose_name="Файл (необязательно)",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="partners/",
                verbose_name="Логотип (необязательно)",
            ),
        ),
    ]
