# Generated by Django 5.1.4 on 2025-09-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_media_file_alter_partner_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/previews/",
                verbose_name="Превью (для видео/документов)",
            ),
        ),
    ]
