# Generated by Django 5.0.7 on 2025-11-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_media_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="format",
            field=models.CharField(
                choices=[("single", "Одна таблица"), ("groups", "Групповой этап")],
                default="single",
                help_text="Выберите формат: одна таблица или групповой этап",
                max_length=20,
                verbose_name="Формат турнира",
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Например: "Группа A", "Группа 1"',
                        max_length=100,
                        verbose_name="Название группы",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "ordering": ["season", "order", "name"],
                "unique_together": {("season", "name")},
            },
        ),
    ]
