# Generated by Django 5.0.2 on 2025-08-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0002_initial"),
        ("core", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирован"),
                            ("live", "В прямом эфире"),
                            ("finished", "Завершен"),
                            ("cancelled", "Отменен"),
                            ("postponed", "Перенесен"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "home_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Голы домашней команды"
                    ),
                ),
                (
                    "away_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Голы гостевой команды"
                    ),
                ),
                (
                    "home_score_ht",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Голы домашней команды (первый тайм)",
                    ),
                ),
                (
                    "away_score_ht",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Голы гостевой команды (первый тайм)",
                    ),
                ),
                (
                    "stadium",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Стадион"
                    ),
                ),
                (
                    "attendance",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Посещаемость"
                    ),
                ),
                (
                    "round",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Тур"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="clubs.club",
                        verbose_name="Гостевая команда",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="clubs.club",
                        verbose_name="Домашняя команда",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матч",
                "verbose_name_plural": "Матчи",
                "ordering": ["-date", "-time"],
                "unique_together": {("home_team", "away_team", "season", "date")},
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minute", models.PositiveIntegerField(verbose_name="Минута")),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("goal", "Гол"),
                            ("penalty", "Пенальти"),
                            ("own_goal", "Автогол"),
                            ("free_kick", "Свободный удар"),
                            ("header", "Головой"),
                        ],
                        default="goal",
                        max_length=20,
                        verbose_name="Тип гола",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "assist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assists",
                        to="players.player",
                        verbose_name="Передача",
                    ),
                ),
                (
                    "scorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals_scored",
                        to="players.player",
                        verbose_name="Забивший",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="clubs.club",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="matches.match",
                        verbose_name="Матч",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гол",
                "verbose_name_plural": "Голы",
                "ordering": ["match", "minute"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("yellow", "Желтая"),
                            ("red", "Красная"),
                            ("second_yellow", "Вторая желтая"),
                        ],
                        max_length=20,
                        verbose_name="Тип карточки",
                    ),
                ),
                ("minute", models.PositiveIntegerField(verbose_name="Минута")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Причина"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="players.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="clubs.club",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="matches.match",
                        verbose_name="Матч",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка",
                "verbose_name_plural": "Карточки",
                "ordering": ["match", "minute"],
            },
        ),
        migrations.CreateModel(
            name="Substitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minute", models.PositiveIntegerField(verbose_name="Минута")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions",
                        to="matches.match",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "player_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions_in",
                        to="players.player",
                        verbose_name="Игрок входящий",
                    ),
                ),
                (
                    "player_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions_out",
                        to="players.player",
                        verbose_name="Игрок выходящий",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions",
                        to="clubs.club",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замена",
                "verbose_name_plural": "Замены",
                "ordering": ["match", "minute"],
            },
        ),
    ]
