# Generated by Django 5.0.2 on 2025-08-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Время"),
        ),
    ]
