# Generated by Django 5.0.2 on 2025-08-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_alter_club_logo"),
        ("core", "0002_management_media_referee_delete_news"),
        ("matches", "0002_alter_match_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("home_team", "away_team", "season")},
        ),
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата"),
        ),
    ]
