# Generated by Django 5.0.2 on 2025-09-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_alter_club_city_alter_coach_first_name_and_more"),
        ("core", "0003_remove_media_description_alter_management_name_and_more"),
        ("matches", "0003_alter_match_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_matches",
                to="clubs.club",
                verbose_name="Гостевая команда",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="clubs.club",
                verbose_name="Домашняя команда",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="core.season",
                verbose_name="Сезон",
            ),
        ),
    ]
