# Generated by Django 5.0.2 on 2025-09-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_alter_match_away_team_alter_match_home_team_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match",
            unique_together=set(),
        ),
    ]
