# Generated by Django 5.0.2 on 2025-09-03 10:22

import django.db.models.deletion
from django.db import migrations, models
import django.db.models.deletion


def create_default_stadium(apps, schema_editor):
    Stadium = apps.get_model('matches', 'Stadium')
    if not Stadium.objects.exists():
        Stadium.objects.create(name='Стадион', city='')


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город/регион')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Стадион',
                'verbose_name_plural': 'Стадионы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='stadium_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.stadium', verbose_name='Стадион (справочник)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.CharField(blank=True, max_length=200, verbose_name='Стадион (название)'),
        ),
    ]
