# Generated by Django 5.0.2 on 2025-09-03 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_remove_club_colors_remove_club_kit_color_away_and_more"),
        ("matches", "0007_match_stadium_ref_alter_match_stadium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="away_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Количество голов гостевой команды",
                null=True,
                verbose_name="Голы гостевой команды",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Команда, играющая в гостях",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_matches",
                to="clubs.club",
                verbose_name="Гостевая команда",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateField(
                default="2025-01-01",
                help_text="ДД-ММ-ГГГГ Дата проведения матча",
                verbose_name="Дата",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Количество голов домашней команды",
                null=True,
                verbose_name="Голы домашней команды",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Команда, принимающая матч дома",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="clubs.club",
                verbose_name="Домашняя команда",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="stadium",
            field=models.CharField(
                blank=True,
                help_text="Название стадиона",
                max_length=200,
                verbose_name="Стадион",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Запланирован"),
                    ("live", "В прямом эфире"),
                    ("finished", "Завершен"),
                    ("cancelled", "Отменен"),
                    ("postponed", "Перенесен"),
                ],
                default="scheduled",
                help_text="Статус матча (запланирован, в эфире, завершен и т.д.)",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="ЧЧ:ММ Время начала матча",
                null=True,
                verbose_name="Время",
            ),
        ),
    ]
