# Generated by Django 5.0.2 on 2025-09-05 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0010_clubapplication"),
        ("matches", "0008_alter_match_away_score_alter_match_away_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                default=None,
                help_text="Команда, играющая в гостях",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_matches",
                to="clubs.club",
                verbose_name="Гостевая команда",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                default=None,
                help_text="Команда, принимающая матч дома",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="clubs.club",
                verbose_name="Домашняя команда",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="stadium_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="matches.stadium",
                verbose_name="Стадион (справочник)",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Назначен"),
                    ("live", "Идёт игра"),
                    ("finished", "Закончен"),
                    ("postponed", "Перенос матча"),
                ],
                default="scheduled",
                help_text="Статус матча (запланирован, в эфире, завершен и т.д.)",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="time",
            field=models.TimeField(
                default="15:00",
                help_text="ЧЧ:ММ Время начала матча",
                verbose_name="Время",
            ),
        ),
    ]
