# Generated by Django 5.1.4 on 2025-09-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_add_assist_model"),
        ("matches", "0009_alter_match_away_team_alter_match_home_team_and_more"),
    ]

    operations = []
