# Generated by Django 5.1.4 on 2025-09-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0012_remove_club_slug"),
        ("matches", "0010_merge_20250914_1937"),
        ("players", "0011_alter_playertransfer_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assist",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assist_events",
                to="players.player",
                verbose_name="Игрок",
            ),
        ),
        migrations.AlterField(
            model_name="assist",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assist_events",
                to="clubs.club",
                verbose_name="Команда",
            ),
        ),
    ]
