# Generated by Django 5.1.4 on 2025-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0011_alter_assist_player_alter_assist_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="address",
            field=models.CharField(blank=True, max_length=300, verbose_name="Адрес"),
        ),
    ]
