# Generated by Django 5.1.4 on 2025-09-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0012_stadium_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadium",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Адрес"
            ),
        ),
    ]
