# Generated by Django 5.0.7 on 2025-11-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_season_format_group"),
        ("matches", "0013_alter_stadium_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Группа для групповых этапов. Если не указана - обычный матч.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_matches",
                to="core.group",
                verbose_name="Группа",
            ),
        ),
    ]
