# Generated by Django 5.0.2 on 2025-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="manager",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="manager",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("president", "Президент"),
                    ("vice_president", "Вице-президент"),
                    ("general_secretary", "Генеральный секретарь"),
                    ("director", "Директор"),
                    ("manager", "Менеджер"),
                ],
                max_length=20,
                verbose_name="Должность",
            ),
        ),
    ]
