# Generated by Django 5.0.2 on 2025-09-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0002_alter_manager_first_name_alter_manager_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Полное имя"
            ),
        ),
    ]
