# Generated by Django 5.0.2 on 2025-09-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_manager_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="name",
        ),
    ]
