# Generated by Django 5.1.4 on 2025-09-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_remove_manager_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Дополнительная информация (например, курирует дисциплинарный комитет)",
                verbose_name="Примечание",
            ),
        ),
    ]
