# Generated by Django 5.1.4 on 2025-09-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_manager_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="bio",
        ),
    ]
